### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by robertnicjoo** [Midtrans/midtrans-php#16]
Hi there,

I wonder with your documentation specifically [this part](https://github.com/Midtrans/midtrans-php#2-how-to-use) .

I am trying to use it in Laravel Framework, I'd installed this package by composer, now what?

1. How should I access to `Midtrans\Config` in my controllers?
2. Is there any package name of aliases that i should add to my configs or what?
3. Is there any `views/model` that I should publish (artisan discover command)?
4. Is there any config names that I should add to `.env` file or even config file (artisan share views)?

> Please provide complete documentation if you try to make a package. _Thank you_

**Comment by rizdaprasetya** [comment]
Hi @robertnicjoo 

Laravel framework itself is just PHP based, both method [explained](https://github.com/Midtrans/midtrans-php#1-installation) will work. You can
- just download as folder and use `require_once`, or 
- install via Composer.

Though if you are aiming for more modern workflow, you should install with composer:

1. `\Midtrans` will automatically be imported as Object/Class in your Laravel project by Composer's autoload.

We suggest you to check these framework specific community discussion if you are not sure how that framework can be used together with Composer, in some case Laravel require you to run `composer dumpautoload` first:
- https://laracasts.com/discuss/channels/general-discussion/using-non-laravel-composer-package-with-laravel?page=1#reply=461608
- https://stackoverflow.com/a/23675376

Answer to question number 2, 3, & 4 is: **No**. 

> Please provide complete documentation if you try to make a package.

Since this is not Laravel/framework specific package, this package is universally compatible with any popular PHP framework, especially those who honor Composer, as the docs already explains the usage. The usage will be Class based. You got a Class that can be configured within your controller, or separated config file.

Thanks.

**Comment by rizdaprasetya** [comment]
Alternatively you can use the community based Laravel specific package, provided by this fine contributor:
https://github.com/firmantr3/laravel-midtrans

Which use this same Midtrans package under the hood, but wrapped in Laravel flavored syntax.

**Comment by rizdaprasetya** [comment]
Closed due to inactivity, please comment if you need further assistance
