### ISSUE TITLE
Whether the transaction is not available, or you typed in the wrong URL.

### ISSUE THREAD

**Issue by robertnicjoo** [Midtrans/midtrans-php#26]
Hi,

What cause to receive this error on snap popup?

```
Whether the transaction is not available, or you typed in the wrong URL.
```

While with my current code if I use snap redirect it works just fine.

![download (2)](https://user-images.githubusercontent.com/8672823/87002195-48b85b80-c1e3-11ea-9b35-a3b16aa039a1.png)

**Comment by Xaxxis** [comment]
Hi @robertnicjoo thank you for reaching out to us, The error happened because Snap.JS didn't get a valid Snap token. Make sure you get an appropriate response from our API. Please visit [our docs](https://beta-docs.midtrans.com/en/snap/integration-guide?id=_1-obtain-transaction-token-on-backend) to get more cleary step guide to obtain Snap token

Thank you
