### ISSUE TITLE
Undefined index: email : Midtrans/Sanitizer.php

### ISSUE THREAD

**Issue by irfanhkm** [Midtrans/midtrans-php#53]
Error Detail:
```
exception: "ErrorException"
file: "/vendor/midtrans/midtrans-php/Midtrans/Sanitizer.php"
line: 67
message: "Undefined index: email"
```

Question:
Is this library not support optional email on customer payload?  refer to https://api-docs.midtrans.com/#item-details-object, the email payload is an optional.

![Screen Shot 2021-08-05 at 5 19 10 PM](https://user-images.githubusercontent.com/30617181/128334265-05d157ee-ec63-446b-8498-89345245b8c0.png)

Thank you.

**Comment by Xaxxis** [comment]
Hi @irfanhkm thank you for reaching out to us. Looks like a valid issue, Basically our library support optional request. This happens cause of some issues in Sanitize feature. The issue was acknowledged by our team, will be fixed on the next release. For a workaround you can disable the sanitize feature, `Config::$isSanitized = false;` or remove the line part of isSanitize feature.

Thank you

**Comment by Xaxxis** [comment]
Resolved, released on a new version. Thank you
